"""empty message

Revision ID: b2c04af9bc9d
Revises: 
Create Date: 2024-12-28 21:10:00.478788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2c04af9bc9d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False, comment='英文单词'),
    sa.Column('part_of_speech', sa.String(length=50), nullable=False, comment='词性'),
    sa.Column('correct_translation', sa.String(length=200), nullable=False, comment='正确翻译'),
    sa.Column('wrong_translation_1', sa.String(length=200), nullable=False, comment='错误翻译1'),
    sa.Column('wrong_translation_2', sa.String(length=200), nullable=False, comment='错误翻译2'),
    sa.Column('wrong_translation_3', sa.String(length=200), nullable=False, comment='错误翻译3'),
    sa.Column('error_count', sa.Integer(), nullable=True, comment='错误次数'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_words_word'), ['word'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('words', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_words_word'))

    op.drop_table('words')
    # ### end Alembic commands ###
